site_name: Александрия 30
site_description: Сборник конспектов который не сгорит!
site_author: Ученики 30ки
site_url: https://30.spb.ru

repo_url: https://github.com/30spb/Alexandria30
repo_name: 30spb/Alexandria30  
edit_uri: tree/main/docs/

copyright: Made with ❤️ from <a href="https://school30.spb.ru/">pml30</a>

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/alexandria_30
      name: Мы в телеге!

nav:
  - Добро пожаловать!: index.md
  - ЧаВо:
    - Ликбез по Александрии: faq/index.md
    - Редакция Александрии: faq/admins.md
  - ...

theme:
  name: material
  language: ru
  features:
    - content.action.edit
    - content.tooltips
    - navigation.path
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/logo.ico
  logo: assets/logo.png

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      locale: ru
      type: timeago
      timezone: Europe/Moscow
  - awesome-pages

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: "#"
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js