site_name: Александрия 30
site_description: Сборник конспектов который не сгорит!
site_author: Ученики 30ки
site_url: http://80.85.241.110:8080/

repo_url: https://github.com/30spb/Alexandria30
repo_name: 30spb/Alexandria30
edit_uri: tree/main/docs/

nav:
  - Добро пожаловать!: index.md
  - ...

theme:
  name: material
  language: ru
  features:
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/logo.png
  logo: assets/logo.png

plugins:
  - search
  - git-revision-date-localized:
      type: custom
      custom_format: "%d.%m.%Y %I:%M"
  - awesome-pages

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
